add possibility to disable dxc
DiligentGraphics/DiligentCore pull request #253
Opened 2021-07-05 12:02 UTC by AndreyMlashkin

Some users may not need DirectXShaderCompiler support.
Introduce a cmake flag to disable it

2021-07-05 14:34 UTC, TheMostDiligent commented
Please rename this option to `DILIGENT_NO_DXC` and move it to the ShaderTools' CMake file.

2021-07-05 14:48 UTC, TheMostDiligent commented
Why do you need to disable it, by the way?

2021-07-06 07:53 UTC, AndreyMlashkin commented
I need to run diligent in a docker container and I need to keep it as small as possible.

2021-07-06 12:39 UTC, AndreyMlashkin commented
Is there a CI problem?
By default, nothing should changed, only if user overrides the flag

2021-07-06 12:46 UTC, azhirnov commented
@AndreyMlashkin DirectX shaders uses DXC to get reflection from DXIL, you should surround this code by macros

2021-07-06 16:43 UTC, TheMostDiligent commented
> Is there a CI problem?

Yes, DX12 backend expects that DXC is always present and there is a build error. It is expected to be the main compiler for DX12. If you disable it, you will not be able to consume DXIL. None of the next-gen DX12 features (mesh shaders, ray tracing, wave operations, etc.) will not work.

> I need to run diligent in a docker container and I need to keep it as small as possible.

You are disabling one file worth of ~1800 lines of code. Not sure this will give you a ton of space savings.
Note that you are not disabling DXC itself, but only the code that calls. The compiler itself is in the System directory or the SDK.

2021-07-06 17:17 UTC, AndreyMlashkin commented
I use vulkan installation from conan, it contains only minimal libs (only vulkanlib actually), there is no dxc compiler at all.
That's why I also want to exclude code, that uses it

2021-07-06 17:25 UTC, TheMostDiligent commented on Graphics/ShaderTools/CMakeLists.txt
> +if(DILIGENT_NO_DXC AND ((PLATFORM_WIN32 AND NOT MINGW_BUILD) OR PLATFORM_UNIVERSAL_WINDOWS OR PLATFORM_LINUX))
Should be `NOT DILIGENT_NO_DXC`

2021-07-06 17:34 UTC, TheMostDiligent commented on Graphics/ShaderTools/CMakeLists.txt
> +set(DILIGENT_NO_DXC FALSE CACHE INTERNAL "Use DirectXShaderCompiler compiler")
I don't think this needs to be a cache variable. If it is internal and not an CMake option, there is no need to define this variable here at all.

2021-07-06 17:35 UTC, TheMostDiligent commented on Graphics/ShaderTools/CMakeLists.txt
> +set(DILIGENT_NO_DXC FALSE CACHE INTERNAL "Use DirectXShaderCompiler compiler")
Besides, this variable defines whether to **disable** using the compiler, not when to use it

2021-07-07 15:12 UTC, TheMostDiligent requested changes

2021-07-07 15:12 UTC, TheMostDiligent commented on Graphics/ShaderTools/CMakeLists.txt
> +set(DILIGENT_NO_DXC FALSE CACHE INTERNAL "Use DirectXShaderCompiler compiler")
Please remove this variable, it is not needed

2021-07-12 09:03 UTC, AndreyMlashkin commented
I have tried to compile my changes only in Windows for different flags.

2021-07-12 18:42 UTC, AndreyMlashkin commented
@TheMostDiligent , I would kindly ask you to start the CI pipeline

2021-07-13 00:44 UTC, TheMostDiligent commented on Graphics/ShaderTools/CMakeLists.txt
> +endif()
This logic is incorrect. On Linux, for example, there is no D3D11 and D3D12 even when neither DILIGENT_NO_DIRECT3D11 nor DILIGENT_NO_DIRECT3D12 is defined, but DXC is still needed.
The correct check is if (D3D11_SUPPORTED or D3D12_SUPPORTED)

2021-07-13 00:44 UTC, TheMostDiligent commented on Graphics/ShaderTools/CMakeLists.txt
> +if (DXC_SUPPORTED AND DXC_NEEDED)
This is also incorrect. DXC is used by Vulkan backend even when there is no D3D11 and D3D12. All high-end tutorials (mesh shaders, ray tracing, hybrid rendering) require DXC compiler in Vulkan mode

2021-07-13 00:47 UTC, TheMostDiligent commented
I am leaning to close this PR as it does not really provide any benefit. Removing one file from the build is not going to give any significant space savings, but complicates the build configuration by a lot. If you don't have DXC on your system, everything will still run fine unless you try to use `SHADER_COMPILER_DXC`. You need to install ATL support for Visual Studio and the file will compile without errors.

2021-07-23 16:15 UTC, closed without merging