WebGPU: Fixed build settings for pthreads (close #583)
DiligentGraphics/DiligentCore pull request #588
Opened 2024-07-29 11:34 UTC by MikhailGorobets

2024-07-29 15:55 UTC, TheMostDiligent requested changes
Looks like gtest also [requires these settings](https://github.com/DiligentGraphics/DiligentCore/actions/runs/10143483209/job/28044934942#step:5:1132).

2024-07-29 15:55 UTC, TheMostDiligent commented on ThirdParty/dawn/CMakeLists.txt
> +    )
We have a helper CMake function [`find_targets_in_directory`](https://github.com/DiligentGraphics/DiligentCore/blob/master/BuildTools/CMake/BuildUtils.cmake#L207)

2024-07-29 18:50 UTC, TheMostDiligent requested changes
Please add the `set_targets_emscripten_properties` function to CMake Utils that will set the required properties on Emscripten platform and no nothing on other:

```CMake
find_targets_in_directory(DAWN_TARGETS ${dawn_SOURCE_DIR})
set_targets_emscripten_properties (${DAWN_TARGETS})
```

2024-07-29 20:30 UTC, TheMostDiligent commented
@MikhailGorobets 
Please create the server startup script file and copy it to the build directory so that the server can be easily started

2024-07-30 04:42 UTC, MikhailGorobets commented
> @MikhailGorobets Please create the server startup script file and copy it to the build directory so that the server can be easily started

This clearly needs to be in the samples module. No one uses SimpleHTTPServer in production

2024-07-30 06:33 UTC, merged